name: Run main.py Weekly

on:
  schedule:
    # Planification : une fois par semaine, le lundi à 08:00 UTC
    - cron: '0 8 * * 1'
  workflow_dispatch: # Permet un lancement manuel si nécessaire

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # Étape 4 : Exécuter le script
      - name: Run main.py
        run: python main.py
